### ISSUE TITLE
Bought the chrome extension

### ISSUE THREAD

**Issue by dsmurrell** [timqian/star-history-plugin#8]
Seems to only do one repo per graph... any way to compare two repos or more with the extension?

**Comment by timqian** [comment]
For now, you can use https://timqian.com/star-history/ to do the comparison.
For the extension, it is not supported yet. Maybe we can add an input box in the dropdown to add new repos or simply add a link to redirect the user to the website to add other repos. Let's see if more people have this need for extension

**Comment by dsmurrell** [comment]
So I bought the extension because the GitHub API rate limit was reached from your server. It would be great to have this functionality added to your extension for this reason.

**Comment by timqian** [comment]
The new extension enabled user to add GitHub token manually, rate limit issue should be solved. And this repo is deprecated, for further problems or suggestions you can create an Issue at https://github.com/timqian/star-history
